---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 14:08
---
print("hello world")
--1.全局变量
b = 10
print(b)
b = nil
print(b)
--2.保留字：
--  and break do else elseif end false for function if in local nil not or repeate return then true until while
--3.lua 对大小写敏感
--4.注释
--单行注释
--c = 12
--多行注释
--[[  多行注释 --]]
