---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 21:17
---
--常规函数
function foo(x)
    return 2*x
end
--等价于匿名函数
foo1 = function(x)
    print(2*x)
    return 2*x
end

print(foo1(20))
