---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 21:19
---
--[[
闭包函数：对于一个内嵌函数，其外围函数中定义的局部变量，我们称之为非局部变量
--]]
--例如
function newfun() -- 外围函数
   local i = 0  ---非局部变量
   ---内嵌函数
   return function()
       i = i + 10
       return i
   end
end
--闭包是指一个函数，加上能让该函数正确访问非局部变量的结构支撑 例如:
c1 = newfun()
print(c1()) --10
print(c1()) --20
print(c1()) --30

c2 = newfun()
print(c2()) --10
print(c2()) --20
print(c2()) --30
--更加上面的输出，我们可以得出c1,c2是相互独立的，互不影响

