---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 21:26
---
--[[
非全局函数
因为函数是第一等公民，所以既可以把它存储到全局变量，也可以存储到表字段和局部变量
--]]
--1.存储到表字段
Libs = {}
Libs.foo = function(x)
    print(x)
end
Libs.foo1 = function(x,y)
    print(x,y)
end
--等价于
Libs1 = {
    foo = function(x) print(x) end,
    foo1 = function(x,y) print(x,y) end
}
--还等价于
Liv = {}
function Liv.foo(x) print(x) end
function Liv.foo1(x,y) print(x,y) end

--调用
Liv.foo(12)
Liv.foo1(100,1000)

Libs.foo(300)
Libs.foo1(200,1000)

Libs1.foo1(200,3444)
Libs1.foo(3444)

function fooLoop(n)
    if n > 0 then
        return fooLoop(n-1)
    end
end
print(fooLoop(1000))