---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 21:49
---
--[[1.协程基础
Lua把所有协程相关的函数都打包到了表coroutine中
coroutine.create 创建一个协程
coroutine.consume z重新开始执行一个协程
coroutine.yield 暂停执行一个协程
coroutine.status 获取协程的执行状态
--]]
--一个简单的例子
co = coroutine.create(function ()
    for i = 1, 3 do
        print("co",i)
        coroutine.yield()
    end
end)
print(co)
print(coroutine.status(co))
coroutine.resume(co) --co 1
print(coroutine.status(co))

coroutine.resume(co) --co 2
coroutine.resume(co) --co 3
coroutine.resume(co) --dead
print(coroutine.status(co)) --dead