---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 14:14
---
--[[Lua 是动态类型语言，变量不要类型定义。Lua 中有 8 个基本类型分别为:nil、boolean、 number、string、userdata、function、thread 和 table。函数 type 可以测试给定变量或者值 的类型--]]
print(type("hello world")) -- string
print(type(10*3)) -- number
print(type(print)) --- function
print(type(type)) --- function
print(type(true)) --- boolean
print(type(nil)) ---nil
print(type(type(X))) ---string

print(type(a)) --- nil

--1. Nil类型
--只有一个值nil 可以删除一个值
a = 100
print(a)
a = nil
print(a)

--2. Booleans 类型
--包含两个值：true,false
b = true
c = false
print(b,c)

--3. Strings值
s1 = "hello world"
s2 = string.gsub(s1,"hello","hahaha")
print(s2)
--\a bell
--\b back space ---- 后退
--\f form feed -- 换页
--\n newline -- 换行
--\r carriage return   -- 回车
--\t horizontal tab  -- 制表
--\v vertical tab
--\\ backslash ---- "\"
--\" double quote -- 双引号
--\' single quote  -- 单引号
--\[   --左中括号
--\]有中括号

--4.Number类型
a = 12
print(a/3)
b = 12.56
print(b)

--5.lua 会自动在string和number之间进行转换
print("10"+1) --11.0
print("10"+"1") --11.0
print("-3.e-10"*2) ---6.e-10
--print("hello"+1) --error

--连接符号(在..左右必须加上空格)
print(10 .. 20) --1020

--line = io.read()
--n = tonumber(line)
--if n == nil then
--    error(line .. " is not number")
--else
--    print(n*3)
--end
print(tostring(10) == "10")
print(10 .. "" == "10")

--6. Fuctions
--lua可以调用lua或者c实现的函数，Lua所有标准库都是用C实现的，标准库包括：
--1.string库 table库，I/O库，OS库，算术库，debug库







