---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 14:40
---
--1.算术运算符
--[[
二元运算符:+ - * /
元运算符：-
--]]
print(10+12) --加法
print(10*23) --乘法
print(10/4) --除法
print(10-56) -- 减法
print(-34) --负数

--2.关系运算符
--< > <= >= == ~=
print(10 < 34)
print(10 > 34)
print(10 == "34")
print(10 ~= "23")
--[[注意：
1.这些操作符返回的结果两种：true，false
2.==和~=比较两个值 如果两个值的类型不一致，lua就认为不一致
--]]
a = {}
a.x = 1
a.y = 0

b = {}
b.x = 1
b.y = 0
print(a == b) --false
c = a
print(a == c) --true

print("2" < "15") --false

--3. 逻辑运算符
--and or not
print(4 and 5) --5
print(4 or 5) -- 4
print(false or 5) --5

xx = 45
x = xx or 34
print(x)
--等价于
if not x then
    x =v
    print("fff" .. x)
end
if x ~= nil then
    print(100)
end

--4. 三目运算符
--(a and b) or c
print(not nil)
print(not false)
print(not 0)
print(not not nil)
--not 的结果只会返回false或者true

--5.连接运算符
--.. --两个点   字符串连接，如果操作数为数字，Lua 将数字转成字符串。
