---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 14:56
---

--表是Lua特有的功能强大的东西，最简单的构造函数是{},用来创建一个空表，可以这样初始化一个数组

data = {"星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天"}
--lua的索引是从1开始
print(data[1])

--构造函数可以使用任何表达式初始化
tab = {math.sin(1), math.sin(2)}
print(tab[1])

--如果想初始化一个表作为record使用
re = {x = 0, y = 100}
print(re.x)
--还可以这样做
res = {}
res.x = 10
res.y = 1000
print(res.x)

opnames = {
  ["+"] = "add",
  ["-"] = "sub",
  ["*"] = "mul",
  ["/"] = "div"
}
print(opnames["+"])
