---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 16:00
---
a = "hello world" .. "hha"
print(a)
a1,a2,a3 = 10,20,30
print(a1,a2,a3)

a4,a5,a6 = 100,200
print(a6) --nil

--创建局部变量
x = 100 --全局变量
local x1 = 1000
while x1 > 300 do
    x1 = x1 -1
    --print(x1)
end
if x1 > 4000 then
    local x1
    x1 = 20
    print(x1)
else
    print(x1)
end
print(x1)
--[[
注意：
1. 尽量使用局部变量
2.避免命名冲突
3.访问局部变量的速度要不全局变量的块
--]]
--划定一个范围
do
    local a = 100
    local b = math.sqrt(20)
    x1 = -b+a/a
    x2 = -b-a/a
end
print(x1,x2)

local y = 100
if y < 100 then
    print(y)
elseif y>100 then
    print(10000)
else
    print("相等")
end

repeat
    y = y-2
    print(y)
until y == 10

for i = 1, 10 do
    print(i)
end
for i = 1, 10, 2 do
    print(i)
end

--泛型for
data = {"星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天"}
for i, v in ipairs(data) do
    print(i,v)
end
--[[
范型 for 和数值 for 有两点相同:
1. 控制变量是局部变量
2. 不要修改控制变量的值
--]]

revDays = {["Sunday"] = 1, ["Monday"] = 2, ["Tuesday"] = 3, ["Wednesday"] = 4,
           ["Thursday"] = 5, ["Friday"] = 6,
           ["Saturday"] = 7}
revDays1 = {}
for i,v in ipairs(revDays) do
    revDays1[v] = i
    print(revDays1[v])
end




