---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 16:16
---

local i = 1
while  i < 100 do
    if i == 60 then
        break
    end
    i = i + 1
    print(i)
end
function foo ()
    return 100
end
print(foo())