---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2019-03-26 21:05
---
--练习1
function concatWords( ... )
    local res = ""
    for i, s in ipairs({ ... }) do
        res = res .. s
    end
    return res
end
print(concatWords("1","2","3","4","5"))

--练习2
function print_all(arr)
    print(table.unpack(arr))
end
print_all({1,2,3,4,5,})

--练习3
function returnTwoAndOtherWords(first, ... )
    print(...)
    return ...
end
returnTwoAndOtherWords(1,2,3,4,5,6,67,7,8,9)

--unpack 把table结构解析成1，2，3，4，5
function prinArrayEles(array)
    local arr = {}
    for i, v in ipairs(array) do
        arr[i] = v
       print(table.unpack(arr))
    end
end
prinArrayEles({1,2,3,4,6,7,8,7})

